name: chipileta_movies_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3
  path: ^1.9.0
  bcrypt: ^1.1.3
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  local_auth: ^3.0.1
  go_router: ^17.3.0
  google_sign_in: ^7.1.1
  audioplayers: ^6.1.0
  intl_phone_field: ^3.2.0
  flutter_local_notifications: ^18.0.1
  youtube_player_iframe: ^6.0.2
  image_picker: ^1.1.2
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/resources/images/ChipiPolloTe.png"
  adaptive_icon_background: "#086A69"
  adaptive_icon_foreground: "lib/resources/images/chipilogo 2.png"

flutter:
  uses-material-design: true
  assets:
    - lib/resources/images/
    - lib/resources/images/google_signin/
    - assets/sounds/
    - .env