// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOiai47TWl5CfsJ2QKqUqFBbUkgXYZ9kk',
    appId: '1:876216140250:web:d1b9f088d4c8899c5680e3',
    messagingSenderId: '876216140250',
    projectId: 'chipileta-movie-app',
    authDomain: 'chipileta-movie-app.firebaseapp.com',
    storageBucket: 'chipileta-movie-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz-fxd8b80kvBkN39Uo_Sm4UWC3Vj0TEA',
    appId: '1:876216140250:android:2d5a2484931de4845680e3',
    messagingSenderId: '876216140250',
    projectId: 'chipileta-movie-app',
    storageBucket: 'chipileta-movie-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtjBeGdpp5sMJOxd3tKTuFPtBhQEz_euA',
    appId: '1:876216140250:ios:a7a4141ed98129185680e3',
    messagingSenderId: '876216140250',
    projectId: 'chipileta-movie-app',
    storageBucket: 'chipileta-movie-app.firebasestorage.app',
    iosClientId: '876216140250-lp422el49lk8r305ja069k08jslbtetk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chipiletaMoviesApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtjBeGdpp5sMJOxd3tKTuFPtBhQEz_euA',
    appId: '1:876216140250:ios:a7a4141ed98129185680e3',
    messagingSenderId: '876216140250',
    projectId: 'chipileta-movie-app',
    storageBucket: 'chipileta-movie-app.firebasestorage.app',
    iosClientId: '876216140250-lp422el49lk8r305ja069k08jslbtetk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chipiletaMoviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOiai47TWl5CfsJ2QKqUqFBbUkgXYZ9kk',
    appId: '1:876216140250:web:21deb28880c73ea75680e3',
    messagingSenderId: '876216140250',
    projectId: 'chipileta-movie-app',
    authDomain: 'chipileta-movie-app.firebaseapp.com',
    storageBucket: 'chipileta-movie-app.firebasestorage.app',
  );
}
